package com.gpustore.notification;

/**
 * Types of notifications generated by the system.
 *
 * @author GPU Store Team
 * @version 1.0.0
 * @since 1.0.0
 */
public enum NotificationType {
    /** Simulated email notification for order completion */
    EMAIL,
    /** System alert for order expiration or errors */
    SYSTEM_ALERT
}
